/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/familias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Familias */
        get: operations["get_familias_familias_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articulos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Articulos */
        get: operations["get_articulos_articulos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Operarios */
        get: operations["get_operarios_operarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operario-familia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Operario Familia */
        get: operations["get_operario_familia_operario_familia_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operario-articulo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Operario Articulo */
        get: operations["get_operario_articulo_operario_articulo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Opls */
        get: operations["get_opls_opls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resumen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Resumen
         * @description Devuelve el número de registros de cada entidad.
         */
        get: operations["get_resumen_resumen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carga": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Carga */
        post: operations["carga_carga_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opls/crear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear Opl Manual */
        post: operations["crear_opl_manual_opls_crear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carga/errores/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exportar Errores Importacion Excel */
        get: operations["exportar_errores_importacion_excel_carga_errores_excel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exportar/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exportar Excel
         * @description Descarga un fichero Excel con las entidades seleccionadas.
         */
        get: operations["exportar_excel_exportar_excel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Repartos */
        get: operations["list_repartos_repartos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos/estado-optimizacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Estado Optimizacion */
        get: operations["get_estado_optimizacion_repartos_estado_optimizacion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos/{semana}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reparto */
        get: operations["get_reparto_repartos__semana__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos/{semana}/progreso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Optimization Progress */
        get: operations["get_optimization_progress_repartos__semana__progreso_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos/{semana}/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Reparto Excel */
        get: operations["export_reparto_excel_repartos__semana__excel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos/{semana}/optimizar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Optimize Week */
        post: operations["optimize_week_repartos__semana__optimizar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos/{semana}/resultado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Optimization Result */
        get: operations["get_optimization_result_repartos__semana__resultado_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos/{semana}/asignaciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Anadir Asignaciones Manuales */
        post: operations["anadir_asignaciones_manuales_repartos__semana__asignaciones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos/{semana}/asignaciones/{id_opl}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modify Assignment */
        patch: operations["modify_assignment_repartos__semana__asignaciones__id_opl__patch"];
        trace?: never;
    };
    "/repartos/{semana}/limpiar-selectivo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Limpiar Selectivo */
        post: operations["limpiar_selectivo_repartos__semana__limpiar_selectivo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos/{semana}/aprobar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Week */
        post: operations["approve_week_repartos__semana__aprobar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActualizarAsignacionRequest */
        ActualizarAsignacionRequest: {
            /** Dni Operario */
            dni_operario?: string | null;
            /** Es Fija */
            es_fija?: boolean | null;
        };
        /** AnadirAsignacionesRequest */
        AnadirAsignacionesRequest: {
            /** Ids Opls */
            ids_opls: string[];
        };
        /** AprobarSemanaRequest */
        AprobarSemanaRequest: {
            /**
             * Semana Destino
             * Format: date
             */
            semana_destino: string;
            /**
             * Con Arrastre
             * @default true
             */
            con_arrastre: boolean;
            /**
             * Incluir No Asignadas En Arrastre
             * @default true
             */
            incluir_no_asignadas_en_arrastre: boolean;
            /**
             * Forzar Obligatorias Pendientes
             * @default false
             */
            forzar_obligatorias_pendientes: boolean;
        };
        /** ArticuloOut */
        ArticuloOut: {
            /** Referencia */
            referencia: string;
            /** Familia */
            familia: string;
            /** Descripcion */
            descripcion: string;
            /** Peso */
            peso: number;
            /** Tiempo Estandar */
            tiempo_estandar: number;
        };
        /** AsignacionDetalleOut */
        AsignacionDetalleOut: {
            /** Id Opl */
            id_opl: string;
            /** Ref Articulo */
            ref_articulo: string;
            /**
             * Nombre Articulo
             * @default
             */
            nombre_articulo: string;
            /**
             * Ref Familia
             * @default
             */
            ref_familia: string;
            /** Cantidad */
            cantidad: number;
            /** Tipo Asignacion */
            tipo_asignacion: string;
            /**
             * Es Fija
             * @default false
             */
            es_fija: boolean;
            /** Dni Operario */
            dni_operario?: string | null;
            /** Nombre Operario */
            nombre_operario?: string | null;
            /** Tiempo Planificado */
            tiempo_planificado: number;
            /** Tiempo Total Teorico */
            tiempo_total_teorico: number;
            /** Es Optima */
            es_optima?: boolean | null;
        };
        /** AsignacionItemOut */
        AsignacionItemOut: {
            /** Id Opl */
            id_opl: string;
            /** Nombre Operario */
            nombre_operario: string;
            /** Dni Operario */
            dni_operario: string;
            /** Tiempo Min */
            tiempo_min: number;
        };
        /** Body_carga_carga_post */
        Body_carga_carga_post: {
            /** Archivo */
            archivo: string;
        };
        /** CargaOperarioOut */
        CargaOperarioOut: {
            /** Nombre */
            nombre: string;
            /** Dni */
            dni: string;
            /** Carga Min */
            carga_min: number;
            /** Capacidad Min */
            capacidad_min: number;
            /** Pct Utilizacion */
            pct_utilizacion: number;
            /**
             * N Articulos
             * @default 0
             */
            n_articulos: number;
            /**
             * Peso Kg
             * @default 0
             */
            peso_kg: number;
        };
        /** CargaOut */
        CargaOut: {
            familias?: components["schemas"]["ImportEntityResult"] | null;
            articulos?: components["schemas"]["ImportEntityResult"] | null;
            operarios?: components["schemas"]["ImportEntityResult"] | null;
            operario_familia?: components["schemas"]["ImportEntityResult"] | null;
            operario_articulo?: components["schemas"]["ImportEntityResult"] | null;
            opls?: components["schemas"]["ImportEntityResult"] | null;
        };
        /** ErrorOut */
        ErrorOut: {
            /** Error */
            error: string;
            /** Detail */
            detail: string;
            /** Code */
            code: number;
        };
        /** EstadoOptimizacionOut */
        EstadoOptimizacionOut: {
            /** Semana En Curso */
            semana_en_curso?: string | null;
            /** Fase */
            fase?: string | null;
            /** Estado */
            estado?: string | null;
            /** Inicio Ts */
            inicio_ts?: number | null;
            /** N Opls */
            n_opls?: number | null;
        };
        /** FamiliaOut */
        FamiliaOut: {
            /** Descripcion */
            descripcion: string;
            /** Experiencia Requerida */
            experiencia_requerida: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportEntityResult */
        ImportEntityResult: {
            /** Importados */
            importados: number;
            /** Omitidos */
            omitidos: number;
            /** Razones */
            razones: {
                [key: string]: number;
            };
        };
        /** LimpiarSelectivoOut */
        LimpiarSelectivoOut: {
            /**
             * Semana
             * Format: date
             */
            semana: string;
            /**
             * Desfijadas
             * @default 0
             */
            desfijadas: number;
            /**
             * Normalizadas
             * @default 0
             */
            normalizadas: number;
            /**
             * Arrastre Eliminados
             * @default 0
             */
            arrastre_eliminados: number;
        };
        /** LimpiarSelectivoRequest */
        LimpiarSelectivoRequest: {
            /**
             * Desfijar
             * @default false
             */
            desfijar: boolean;
            /**
             * Normalizar Obligatorias
             * @default false
             */
            normalizar_obligatorias: boolean;
            /**
             * Eliminar Arrastre
             * @default false
             */
            eliminar_arrastre: boolean;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MetricasOut */
        MetricasOut: {
            /** N Opls Totales */
            n_opls_totales: number;
            /** N Asignadas */
            n_asignadas: number;
            /** N Optimas */
            n_optimas: number;
            /** Media Exp No Optimos */
            media_exp_no_optimos?: number | null;
            /** Media Tiempo Real */
            media_tiempo_real?: number | null;
            /** Total Asignado Min */
            total_asignado_min: number;
            /** Total Capacidad Min */
            total_capacidad_min: number;
            /** Pct Utilizacion Global */
            pct_utilizacion_global: number;
        };
        /** OperarioArticuloOut */
        OperarioArticuloOut: {
            /** Ref Articulo */
            ref_articulo: string;
            /** Dni Operario */
            dni_operario: string;
            /** Tiempo Estimado */
            tiempo_estimado: number;
        };
        /** OperarioFamiliaOut */
        OperarioFamiliaOut: {
            /** Dni Operario */
            dni_operario: string;
            /** Familia */
            familia: string;
            /** Experiencia */
            experiencia: number;
        };
        /** OperarioOut */
        OperarioOut: {
            /** Dni */
            dni: string;
            /** Nombre Completo */
            nombre_completo: string;
            /** Horas Semanales */
            horas_semanales: number;
        };
        /** OplCrearManualRequest */
        OplCrearManualRequest: {
            /** Ref Articulo */
            ref_articulo: string;
            /** Cantidad */
            cantidad: number;
        };
        /** OplOut */
        OplOut: {
            /** Id */
            id: string;
            /** Ref Articulo */
            ref_articulo: string;
            /** Cantidad */
            cantidad: number;
            /** Tiempo Estimado */
            tiempo_estimado: number;
            /** Asignado A */
            asignado_a?: string | null;
        };
        /** OptimizarSemanaRequest */
        OptimizarSemanaRequest: {
            /** Ids Opls */
            ids_opls?: string[] | null;
            /**
             * Tiempo Maximo Min
             * @default 5
             */
            tiempo_maximo_min: number;
            /** @default balanceado */
            perfil: components["schemas"]["PerfilDelta"];
        };
        /**
         * PerfilDelta
         * @enum {string}
         */
        PerfilDelta: "produccion" | "balanceado" | "personas";
        /** RepartoDetalleOut */
        RepartoDetalleOut: {
            /**
             * Semana
             * Format: date
             */
            semana: string;
            /** Aprobado */
            aprobado: boolean;
            /** Fecha Aprobacion */
            fecha_aprobacion?: string | null;
            /** Estado Base */
            estado_base?: string | null;
            /** Estado Eficiencia */
            estado_eficiencia?: string | null;
            /** Estado Equidad Peso */
            estado_equidad_peso?: string | null;
            /** Estado Equidad Articulos */
            estado_equidad_articulos?: string | null;
            /** Asignaciones */
            asignaciones: components["schemas"]["AsignacionDetalleOut"][];
        };
        /** RepartoResumenOut */
        RepartoResumenOut: {
            /**
             * Semana
             * Format: date
             */
            semana: string;
            /** Aprobado */
            aprobado: boolean;
            /** Fecha Aprobacion */
            fecha_aprobacion?: string | null;
            /** N Asignadas */
            n_asignadas: number;
            /** N Pendientes */
            n_pendientes: number;
            /** Estado Base */
            estado_base?: string | null;
            /** Estado Eficiencia */
            estado_eficiencia?: string | null;
            /** Estado Equidad Peso */
            estado_equidad_peso?: string | null;
            /** Estado Equidad Articulos */
            estado_equidad_articulos?: string | null;
            /** Modo Aprobacion */
            modo_aprobacion?: string | null;
            /** Semana Destino */
            semana_destino?: string | null;
            /** Incluir No Asignadas En Arrastre */
            incluir_no_asignadas_en_arrastre?: boolean | null;
            /** Obligatorias Forzadas */
            obligatorias_forzadas?: boolean | null;
            /** Validacion Errores */
            validacion_errores?: string[] | null;
            /** Validacion Advertencias */
            validacion_advertencias?: string[] | null;
            /** Limpieza Aplicada */
            limpieza_aplicada?: boolean | null;
            /** No Asignadas Eliminadas Origen */
            no_asignadas_eliminadas_origen?: number | null;
            /** Perfil */
            perfil?: string | null;
        };
        /** ResultadoOut */
        ResultadoOut: {
            /** Estado */
            estado: string;
            /** Estado Base */
            estado_base: string;
            /** Estado Eficiencia */
            estado_eficiencia: string;
            /** Estado Equidad Peso */
            estado_equidad_peso: string;
            /** Estado Equidad Articulos */
            estado_equidad_articulos: string;
            /** Asignaciones */
            asignaciones: components["schemas"]["AsignacionItemOut"][];
            /** No Asignadas Sin Capacidad */
            no_asignadas_sin_capacidad: string[];
            /** No Asignadas Sin Candidato */
            no_asignadas_sin_candidato: string[];
            /** Cargas */
            cargas: components["schemas"]["CargaOperarioOut"][];
            metricas: components["schemas"]["MetricasOut"];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_familias_familias_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamiliaOut"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_articulos_articulos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticuloOut"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_operarios_operarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperarioOut"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_operario_familia_operario_familia_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperarioFamiliaOut"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_operario_articulo_operario_articulo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperarioArticuloOut"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_opls_opls_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OplOut"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_resumen_resumen_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    carga_carga_post: {
        parameters: {
            query?: {
                modo?: string;
                entidades?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_carga_carga_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CargaOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    crear_opl_manual_opls_crear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OplCrearManualRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OplOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    exportar_errores_importacion_excel_carga_errores_excel_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    exportar_excel_exportar_excel_get: {
        parameters: {
            query?: {
                entidades?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    list_repartos_repartos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepartoResumenOut"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_estado_optimizacion_repartos_estado_optimizacion_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstadoOptimizacionOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_reparto_repartos__semana__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semana: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepartoDetalleOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_optimization_progress_repartos__semana__progreso_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semana: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    export_reparto_excel_repartos__semana__excel_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semana: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    optimize_week_repartos__semana__optimizar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semana: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizarSemanaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_optimization_result_repartos__semana__resultado_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semana: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    anadir_asignaciones_manuales_repartos__semana__asignaciones_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semana: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnadirAsignacionesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    modify_assignment_repartos__semana__asignaciones__id_opl__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semana: string;
                id_opl: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarAsignacionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepartoDetalleOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    limpiar_selectivo_repartos__semana__limpiar_selectivo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semana: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LimpiarSelectivoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LimpiarSelectivoOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    approve_week_repartos__semana__aprobar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semana: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AprobarSemanaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepartoResumenOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
}
