/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Autentica al usuario y devuelve un JWT.
         *
         *     Args:
         *         body: Credenciales (usuario y contraseña).
         *
         *     Returns:
         *         ``TokenResponse`` con el access token.
         *
         *     Raises:
         *         AuthenticationError: si las credenciales son incorrectas (→ 401).
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Devuelve el usuario asociado al token de la petición.
         *
         *     Args:
         *         username: Usuario extraído del Bearer token por la dependencia.
         *
         *     Returns:
         *         ``{"username": <usuario>}``.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Comprueba que el servicio está vivo.
         *
         *     Returns:
         *         ``{"status": "ok"}`` con código 200 si la API responde.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/familias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Familias
         * @description Lista todas las familias con su experiencia requerida.
         */
        get: operations["get_familias_familias_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articulos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Articulos
         * @description Lista todos los artículos recorriendo familias, con peso y tiempo estándar.
         */
        get: operations["get_articulos_articulos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Operarios
         * @description Lista todos los operarios con su capacidad semanal en horas.
         */
        get: operations["get_operarios_operarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operario-familia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Operario Familia
         * @description Lista las cualificaciones (experiencia por familia) de cada operario.
         */
        get: operations["get_operario_familia_operario_familia_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operario-articulo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Operario Articulo
         * @description Lista los tiempos específicos por artículo definidos para cada operario.
         */
        get: operations["get_operario_articulo_operario_articulo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Opls
         * @description Lista todas las OPLs con su tiempo estimado y el operario asignado, si lo hay.
         */
        get: operations["get_opls_opls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resumen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Resumen
         * @description Devuelve el número de registros de cada entidad.
         */
        get: operations["get_resumen_resumen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carga": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Carga
         * @description Importa datos maestros desde un Excel (única vía de alta/modificación).
         *
         *     Args:
         *             archivo: Fichero Excel subido con las hojas de datos maestros.
         *             modo: ``"actualizar"`` (merge) o ``"reemplazar"`` (sustituye).
         *             entidades: Subconjunto de entidades a importar; vacío = todas.
         *
         *     Returns:
         *             ``CargaOut`` con importados/omitidos por entidad. Los errores de detalle
         *             quedan disponibles para descargar vía ``/carga/errores/excel``.
         *
         *     Raises:
         *             DomainValidationError: si el modo o alguna entidad no son válidos.
         */
        post: operations["carga_carga_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opls/crear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crear Opl Manual
         * @description Crea una OPL manualmente (id autogenerado con prefijo ``MAN``).
         *
         *     Args:
         *         body: Referencia de artículo y cantidad a producir.
         *
         *     Returns:
         *         La OPL creada (``OplOut``), sin operario asignado.
         */
        post: operations["crear_opl_manual_opls_crear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carga/errores/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exportar Errores Importacion Excel
         * @description Descarga en Excel los errores de la última importación realizada.
         *
         *     Returns:
         *             ``StreamingResponse`` con el ``.xlsx`` de errores.
         *
         *     Raises:
         *             NotFoundError: si no hay errores registrados de una importación previa.
         */
        get: operations["exportar_errores_importacion_excel_carga_errores_excel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exportar/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exportar Excel
         * @description Descarga un fichero Excel con las entidades seleccionadas.
         */
        get: operations["exportar_excel_exportar_excel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Repartos
         * @description Lista el resumen de todos los repartos existentes.
         */
        get: operations["list_repartos_repartos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos/estado-optimizacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Estado Optimizacion
         * @description Devuelve el estado global del solver (semana en curso y progreso, si hay).
         */
        get: operations["get_estado_optimizacion_repartos_estado_optimizacion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos/{semana}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Reparto
         * @description Devuelve el detalle del reparto de una semana.
         *
         *     Args:
         *         semana: Lunes ISO de la semana.
         *
         *     Returns:
         *         El detalle del reparto (``RepartoDetalleOut``).
         */
        get: operations["get_reparto_repartos__semana__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos/{semana}/progreso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Optimization Progress
         * @description Devuelve el progreso del solver para una semana concreta.
         *
         *     Args:
         *         semana: Lunes ISO de la semana.
         *
         *     Returns:
         *         Snapshot del progreso si esa semana se está optimizando, o un estado
         *         ``SIN_DATOS`` si el solver está en otra semana o inactivo.
         */
        get: operations["get_optimization_progress_repartos__semana__progreso_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos/{semana}/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Reparto Excel
         * @description Exporta el reparto de una semana como fichero Excel descargable.
         *
         *     Args:
         *         semana: Lunes ISO de la semana.
         *
         *     Returns:
         *         ``StreamingResponse`` con el ``.xlsx`` del reparto.
         *
         *     Raises:
         *         NotFoundError: si no existe el reparto de esa semana.
         */
        get: operations["export_reparto_excel_repartos__semana__excel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos/{semana}/optimizar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Optimize Week
         * @description Lanza la optimización de una semana en un subproceso (respuesta 202).
         *
         *     Valida que no haya otra optimización en curso ni semanas anteriores sin
         *     aprobar, filtra las OPLs ya comprometidas en otras semanas y arranca el
         *     solver en segundo plano; el progreso se consulta aparte.
         *
         *     Args:
         *         semana: Lunes ISO de la semana a optimizar.
         *         req: Parámetros (OPLs, presupuesto de tiempo y perfil).
         *
         *     Raises:
         *         ConflictError: si ya hay una optimización activa o la semana anterior
         *             sigue pendiente de aprobación.
         */
        post: operations["optimize_week_repartos__semana__optimizar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos/{semana}/resultado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Optimization Result
         * @description Devuelve el resultado de la última optimización de una semana.
         *
         *     Args:
         *         semana: Lunes ISO de la semana.
         *
         *     Returns:
         *         El resultado (``ResultadoOut``) con asignaciones, cargas y métricas.
         *
         *     Raises:
         *         ConflictError: si la optimización de esa semana sigue en curso.
         *         NotFoundError: si no hay resultado cacheado para la semana.
         */
        get: operations["get_optimization_result_repartos__semana__resultado_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos/{semana}/asignaciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Anadir Asignaciones Manuales
         * @description Añade manualmente OPLs (sin asignar) al reparto de una semana.
         *
         *     Args:
         *         semana: Lunes ISO de la semana.
         *         req: Lista de ids de OPL a incorporar.
         *
         *     Returns:
         *         ``{"creadas": <n>}`` con el número de asignaciones creadas.
         */
        post: operations["anadir_asignaciones_manuales_repartos__semana__asignaciones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos/{semana}/asignaciones/{id_opl}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Modify Assignment
         * @description Modifica el operario y/o el flag de fijación de una asignación.
         *
         *     Invalida el resultado cacheado del solver y devuelve el reparto actualizado.
         *
         *     Args:
         *         semana: Lunes ISO de la semana.
         *         id_opl: Identificador de la OPL a modificar.
         *         req: Nuevo operario y/o valor de ``es_fija``.
         *
         *     Returns:
         *         El detalle actualizado del reparto (``RepartoDetalleOut``).
         *
         *     Raises:
         *         NotFoundError: si no existe el reparto de esa semana.
         */
        patch: operations["modify_assignment_repartos__semana__asignaciones__id_opl__patch"];
        trace?: never;
    };
    "/repartos/{semana}/limpiar-selectivo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Limpiar Selectivo
         * @description Aplica operaciones de limpieza selectiva sobre el reparto de una semana.
         *
         *     Permite desfijar asignaciones, normalizar obligatorias y/o eliminar arrastres.
         *
         *     Args:
         *         semana: Lunes ISO de la semana.
         *         req: Operaciones de limpieza a aplicar.
         *
         *     Returns:
         *         ``LimpiarSelectivoOut`` con el recuento de filas afectadas por operación.
         */
        post: operations["limpiar_selectivo_repartos__semana__limpiar_selectivo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repartos/{semana}/aprobar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Week
         * @description Aprueba el reparto de una semana y, opcionalmente, genera el arrastre.
         *
         *     Consolida la semana y traslada el trabajo pendiente a ``semana_destino``.
         *
         *     Args:
         *         semana: Lunes ISO de la semana a aprobar.
         *         req: Semana destino y opciones de arrastre/forzado.
         *
         *     Returns:
         *         El resumen del reparto aprobado (``RepartoResumenOut``) enriquecido con
         *         los metadatos de la aprobación.
         */
        post: operations["approve_week_repartos__semana__aprobar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActualizarAsignacionRequest
         * @description Cambios manuales sobre una asignación: operario y/o flag de fijación.
         */
        ActualizarAsignacionRequest: {
            /** Dni Operario */
            dni_operario?: string | null;
            /** Es Fija */
            es_fija?: boolean | null;
        };
        /**
         * AnadirAsignacionesRequest
         * @description Petición para añadir OPLs al reparto de una semana (lista no vacía).
         */
        AnadirAsignacionesRequest: {
            /** Ids Opls */
            ids_opls: string[];
        };
        /**
         * AprobarSemanaRequest
         * @description Parámetros de aprobación de una semana y de la generación de arrastre.
         */
        AprobarSemanaRequest: {
            /**
             * Semana Destino
             * Format: date
             */
            semana_destino: string;
            /**
             * Con Arrastre
             * @default true
             */
            con_arrastre: boolean;
            /**
             * Incluir No Asignadas En Arrastre
             * @default true
             */
            incluir_no_asignadas_en_arrastre: boolean;
            /**
             * Forzar Obligatorias Pendientes
             * @default false
             */
            forzar_obligatorias_pendientes: boolean;
        };
        /**
         * ArticuloOut
         * @description Artículo con su familia, peso unitario y tiempo estándar de fabricación.
         */
        ArticuloOut: {
            /** Referencia */
            referencia: string;
            /** Familia */
            familia: string;
            /** Descripcion */
            descripcion: string;
            /** Peso */
            peso: number;
            /** Tiempo Estandar */
            tiempo_estandar: number;
        };
        /**
         * AsignacionDetalleOut
         * @description Fila detallada de un reparto: OPL, artículo, operario y si es óptima.
         */
        AsignacionDetalleOut: {
            /** Id Opl */
            id_opl: string;
            /** Ref Articulo */
            ref_articulo: string;
            /**
             * Nombre Articulo
             * @default
             */
            nombre_articulo: string;
            /**
             * Ref Familia
             * @default
             */
            ref_familia: string;
            /** Cantidad */
            cantidad: number;
            /** Tipo Asignacion */
            tipo_asignacion: string;
            /**
             * Es Fija
             * @default false
             */
            es_fija: boolean;
            /** Dni Operario */
            dni_operario?: string | null;
            /** Nombre Operario */
            nombre_operario?: string | null;
            /** Tiempo Planificado */
            tiempo_planificado: number;
            /** Tiempo Total Teorico */
            tiempo_total_teorico: number;
            /** Es Optima */
            es_optima?: boolean | null;
        };
        /**
         * AsignacionItemOut
         * @description Una asignación del resultado del solver: OPL → operario, con sus minutos.
         */
        AsignacionItemOut: {
            /** Id Opl */
            id_opl: string;
            /** Nombre Operario */
            nombre_operario: string;
            /** Dni Operario */
            dni_operario: string;
            /** Tiempo Min */
            tiempo_min: number;
        };
        /** Body_carga_carga_post */
        Body_carga_carga_post: {
            /** Archivo */
            archivo: string;
        };
        /**
         * CargaOperarioOut
         * @description Carga resultante de un operario: minutos, capacidad, utilización y aportes.
         */
        CargaOperarioOut: {
            /** Nombre */
            nombre: string;
            /** Dni */
            dni: string;
            /** Carga Min */
            carga_min: number;
            /** Capacidad Min */
            capacidad_min: number;
            /** Pct Utilizacion */
            pct_utilizacion: number;
            /**
             * N Articulos
             * @default 0
             */
            n_articulos: number;
            /**
             * Peso Kg
             * @default 0
             */
            peso_kg: number;
        };
        /**
         * CargaOut
         * @description Resumen de la importación masiva, con un resultado por tipo de entidad.
         */
        CargaOut: {
            familias?: components["schemas"]["ImportEntityResult"] | null;
            articulos?: components["schemas"]["ImportEntityResult"] | null;
            operarios?: components["schemas"]["ImportEntityResult"] | null;
            operario_familia?: components["schemas"]["ImportEntityResult"] | null;
            operario_articulo?: components["schemas"]["ImportEntityResult"] | null;
            opls?: components["schemas"]["ImportEntityResult"] | null;
        };
        /**
         * ErrorOut
         * @description Cuerpo de error uniforme de la API: tipo, detalle y código HTTP.
         */
        ErrorOut: {
            /** Error */
            error: string;
            /** Detail */
            detail: string;
            /** Code */
            code: number;
        };
        /**
         * EstadoOptimizacionOut
         * @description Estado global del solver: semana en curso y progreso, o vacío si está inactivo.
         */
        EstadoOptimizacionOut: {
            /** Semana En Curso */
            semana_en_curso?: string | null;
            /** Fase */
            fase?: string | null;
            /** Estado */
            estado?: string | null;
            /** Inicio Ts */
            inicio_ts?: number | null;
            /** N Opls */
            n_opls?: number | null;
        };
        /**
         * FamiliaOut
         * @description Familia de artículos con su nivel de experiencia requerido.
         */
        FamiliaOut: {
            /** Descripcion */
            descripcion: string;
            /** Experiencia Requerida */
            experiencia_requerida: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImportEntityResult
         * @description Resultado de importar una entidad: altas, modificaciones, eliminaciones y omisiones.
         */
        ImportEntityResult: {
            /** Anadidas */
            anadidas: number;
            /** Modificadas */
            modificadas: number;
            /**
             * Eliminados
             * @default 0
             */
            eliminados: number;
            /**
             * Conservados En Uso
             * @default 0
             */
            conservados_en_uso: number;
            /** Omitidos */
            omitidos: number;
            /** Razones */
            razones: {
                [key: string]: number;
            };
        };
        /**
         * LimpiarSelectivoOut
         * @description Recuento de filas afectadas por cada operación de limpieza selectiva.
         */
        LimpiarSelectivoOut: {
            /**
             * Semana
             * Format: date
             */
            semana: string;
            /**
             * Desfijadas
             * @default 0
             */
            desfijadas: number;
            /**
             * Normalizadas
             * @default 0
             */
            normalizadas: number;
            /**
             * Arrastre Eliminados
             * @default 0
             */
            arrastre_eliminados: number;
        };
        /**
         * LimpiarSelectivoRequest
         * @description Operaciones de limpieza selectiva a aplicar sobre el reparto de una semana.
         */
        LimpiarSelectivoRequest: {
            /**
             * Desfijar
             * @default false
             */
            desfijar: boolean;
            /**
             * Normalizar Obligatorias
             * @default false
             */
            normalizar_obligatorias: boolean;
            /**
             * Eliminar Arrastre
             * @default false
             */
            eliminar_arrastre: boolean;
        };
        /**
         * LoginRequest
         * @description Cuerpo de la petición de login con las credenciales del usuario.
         */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * MetricasOut
         * @description Métricas globales de calidad y utilización de un reparto optimizado.
         */
        MetricasOut: {
            /** N Opls Totales */
            n_opls_totales: number;
            /** N Asignadas */
            n_asignadas: number;
            /** N Optimas */
            n_optimas: number;
            /** Media Exp No Optimos */
            media_exp_no_optimos?: number | null;
            /** Media Tiempo Real */
            media_tiempo_real?: number | null;
            /** Total Asignado Min */
            total_asignado_min: number;
            /** Total Capacidad Min */
            total_capacidad_min: number;
            /** Pct Utilizacion Global */
            pct_utilizacion_global: number;
        };
        /**
         * OperarioArticuloOut
         * @description Tiempo específico que un operario tarda en un artículo concreto.
         */
        OperarioArticuloOut: {
            /** Ref Articulo */
            ref_articulo: string;
            /** Dni Operario */
            dni_operario: string;
            /** Tiempo Estimado */
            tiempo_estimado: number;
        };
        /**
         * OperarioFamiliaOut
         * @description Cualificación de un operario en una familia (su experiencia).
         */
        OperarioFamiliaOut: {
            /** Dni Operario */
            dni_operario: string;
            /** Familia */
            familia: string;
            /** Experiencia */
            experiencia: number;
        };
        /**
         * OperarioOut
         * @description Operario con su capacidad semanal en horas.
         */
        OperarioOut: {
            /** Dni */
            dni: string;
            /** Nombre Completo */
            nombre_completo: string;
            /** Horas Semanales */
            horas_semanales: number;
        };
        /**
         * OplCrearManualRequest
         * @description Datos para crear una OPL manual: artículo y cantidad (> 0).
         */
        OplCrearManualRequest: {
            /** Ref Articulo */
            ref_articulo: string;
            /** Cantidad */
            cantidad: number;
        };
        /**
         * OplOut
         * @description Orden de producción con su tiempo estimado y el operario asignado, si lo hay.
         */
        OplOut: {
            /** Id */
            id: string;
            /** Ref Articulo */
            ref_articulo: string;
            /** Cantidad */
            cantidad: number;
            /** Tiempo Estimado */
            tiempo_estimado: number;
            /** Asignado A */
            asignado_a?: string | null;
        };
        /**
         * OptimizarSemanaRequest
         * @description Parámetros de la petición de optimización de una semana.
         */
        OptimizarSemanaRequest: {
            /** Ids Opls */
            ids_opls?: string[] | null;
            /**
             * Tiempo Maximo Min
             * @default 5
             */
            tiempo_maximo_min: number;
            /** @default balanceado */
            perfil: components["schemas"]["PerfilDelta"];
        };
        /**
         * PerfilDelta
         * @description Perfil de optimización: cuánta calidad se sacrifica a favor de la equidad.
         * @enum {string}
         */
        PerfilDelta: "produccion" | "balanceado" | "personas";
        /**
         * RepartoDetalleOut
         * @description Detalle completo de un reparto: cabecera de estados y lista de asignaciones.
         */
        RepartoDetalleOut: {
            /**
             * Semana
             * Format: date
             */
            semana: string;
            /** Aprobado */
            aprobado: boolean;
            /** Fecha Aprobacion */
            fecha_aprobacion?: string | null;
            /** Estado Base */
            estado_base?: string | null;
            /** Estado Eficiencia */
            estado_eficiencia?: string | null;
            /** Estado Equidad Peso */
            estado_equidad_peso?: string | null;
            /** Estado Equidad Articulos */
            estado_equidad_articulos?: string | null;
            /** Asignaciones */
            asignaciones: components["schemas"]["AsignacionDetalleOut"][];
        };
        /**
         * RepartoResumenOut
         * @description Resumen de un reparto: totales, estados de las fases y metadatos de aprobación.
         */
        RepartoResumenOut: {
            /**
             * Semana
             * Format: date
             */
            semana: string;
            /** Aprobado */
            aprobado: boolean;
            /** Fecha Aprobacion */
            fecha_aprobacion?: string | null;
            /** N Asignadas */
            n_asignadas: number;
            /** N Pendientes */
            n_pendientes: number;
            /** Estado Base */
            estado_base?: string | null;
            /** Estado Eficiencia */
            estado_eficiencia?: string | null;
            /** Estado Equidad Peso */
            estado_equidad_peso?: string | null;
            /** Estado Equidad Articulos */
            estado_equidad_articulos?: string | null;
            /** Modo Aprobacion */
            modo_aprobacion?: string | null;
            /** Semana Destino */
            semana_destino?: string | null;
            /** Incluir No Asignadas En Arrastre */
            incluir_no_asignadas_en_arrastre?: boolean | null;
            /** Obligatorias Forzadas */
            obligatorias_forzadas?: boolean | null;
            /** Validacion Errores */
            validacion_errores?: string[] | null;
            /** Validacion Advertencias */
            validacion_advertencias?: string[] | null;
            /** Limpieza Aplicada */
            limpieza_aplicada?: boolean | null;
            /** No Asignadas Eliminadas Origen */
            no_asignadas_eliminadas_origen?: number | null;
            /** Perfil */
            perfil?: string | null;
        };
        /**
         * ResultadoOut
         * @description Resultado completo de una optimización: estados, asignaciones, cargas y métricas.
         */
        ResultadoOut: {
            /** Estado */
            estado: string;
            /** Estado Base */
            estado_base: string;
            /** Estado Eficiencia */
            estado_eficiencia: string;
            /** Estado Equidad Peso */
            estado_equidad_peso: string;
            /** Estado Equidad Articulos */
            estado_equidad_articulos: string;
            /** Asignaciones */
            asignaciones: components["schemas"]["AsignacionItemOut"][];
            /** No Asignadas Sin Capacidad */
            no_asignadas_sin_capacidad: string[];
            /** No Asignadas Sin Candidato */
            no_asignadas_sin_candidato: string[];
            /** Cargas */
            cargas: components["schemas"]["CargaOperarioOut"][];
            metricas: components["schemas"]["MetricasOut"];
        };
        /**
         * TokenResponse
         * @description Respuesta del login con el JWT emitido y su tipo (siempre ``bearer``).
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_familias_familias_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamiliaOut"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_articulos_articulos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticuloOut"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_operarios_operarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperarioOut"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_operario_familia_operario_familia_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperarioFamiliaOut"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_operario_articulo_operario_articulo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperarioArticuloOut"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_opls_opls_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OplOut"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_resumen_resumen_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    carga_carga_post: {
        parameters: {
            query?: {
                modo?: string;
                entidades?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_carga_carga_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CargaOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    crear_opl_manual_opls_crear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OplCrearManualRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OplOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    exportar_errores_importacion_excel_carga_errores_excel_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    exportar_excel_exportar_excel_get: {
        parameters: {
            query?: {
                entidades?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    list_repartos_repartos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepartoResumenOut"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_estado_optimizacion_repartos_estado_optimizacion_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstadoOptimizacionOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_reparto_repartos__semana__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semana: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepartoDetalleOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_optimization_progress_repartos__semana__progreso_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semana: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    export_reparto_excel_repartos__semana__excel_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semana: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    optimize_week_repartos__semana__optimizar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semana: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizarSemanaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_optimization_result_repartos__semana__resultado_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semana: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    anadir_asignaciones_manuales_repartos__semana__asignaciones_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semana: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnadirAsignacionesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    modify_assignment_repartos__semana__asignaciones__id_opl__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semana: string;
                id_opl: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarAsignacionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepartoDetalleOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    limpiar_selectivo_repartos__semana__limpiar_selectivo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semana: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LimpiarSelectivoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LimpiarSelectivoOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    approve_week_repartos__semana__aprobar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semana: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AprobarSemanaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepartoResumenOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
}
