"""initial

Revision ID: a9929a858140
Revises: 
Create Date: 2026-05-28 09:22:30.199026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9929a858140'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('familias',
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('experiencia_requerida', sa.Integer(), nullable=False),
    sa.CheckConstraint('experiencia_requerida BETWEEN 1 AND 4', name='check_experiencia_requerida_1_4'),
    sa.PrimaryKeyConstraint('descripcion')
    )
    op.create_table('operarios',
    sa.Column('dni', sa.String(), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=False),
    sa.Column('horas_semanales', sa.Float(), nullable=False),
    sa.CheckConstraint('horas_semanales >= 0', name='check_capacidad_no_negativa'),
    sa.PrimaryKeyConstraint('dni')
    )
    op.create_table('repartos',
    sa.Column('semana', sa.Date(), nullable=False),
    sa.Column('aprobado', sa.Boolean(), nullable=False),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('estado_base', sa.String(length=20), nullable=True),
    sa.Column('estado_eficiencia', sa.String(length=20), nullable=True),
    sa.Column('estado_equidad_peso', sa.String(length=20), nullable=True),
    sa.Column('estado_equidad_articulos', sa.String(length=20), nullable=True),
    sa.Column('cota_eficiencia', sa.Float(), nullable=True),
    sa.Column('valor_eficiencia', sa.Float(), nullable=True),
    sa.Column('perfil', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('semana')
    )
    op.create_table('usuarios',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('articulos',
    sa.Column('referencia', sa.String(), nullable=False),
    sa.Column('familia', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('tiempo_estandar', sa.Float(), nullable=False),
    sa.CheckConstraint('peso > 0', name='check_peso_positivo'),
    sa.CheckConstraint('tiempo_estandar > 0', name='check_tiempo_estandar_positivo'),
    sa.ForeignKeyConstraint(['familia'], ['familias.descripcion'], ),
    sa.PrimaryKeyConstraint('referencia')
    )
    op.create_table('operario_familia',
    sa.Column('dni_operario', sa.String(), nullable=False),
    sa.Column('familia', sa.String(), nullable=False),
    sa.Column('experiencia', sa.Integer(), nullable=False),
    sa.CheckConstraint('experiencia BETWEEN 1 AND 4', name='check_experiencia_1_4'),
    sa.ForeignKeyConstraint(['dni_operario'], ['operarios.dni'], ),
    sa.ForeignKeyConstraint(['familia'], ['familias.descripcion'], ),
    sa.PrimaryKeyConstraint('dni_operario', 'familia')
    )
    op.create_table('operario_articulo',
    sa.Column('ref_articulo', sa.String(), nullable=False),
    sa.Column('dni_operario', sa.String(), nullable=False),
    sa.Column('tiempo_estimado', sa.Float(), nullable=False),
    sa.CheckConstraint('tiempo_estimado > 0', name='check_tiempo_estimado_positivo'),
    sa.ForeignKeyConstraint(['dni_operario'], ['operarios.dni'], ),
    sa.ForeignKeyConstraint(['ref_articulo'], ['articulos.referencia'], ),
    sa.PrimaryKeyConstraint('ref_articulo', 'dni_operario')
    )
    op.create_table('opls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ref_articulo', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='check_cantidad_positiva'),
    sa.ForeignKeyConstraint(['ref_articulo'], ['articulos.referencia'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asignaciones_opl',
    sa.Column('id_opl', sa.String(), nullable=False),
    sa.Column('semana', sa.Date(), nullable=False),
    sa.Column('dni_operario', sa.String(), nullable=True),
    sa.Column('tipo_asignacion', sa.Enum('NORMAL', 'OBLIGATORIA', 'ARRASTRE', name='tipoasignacion', native_enum=False), nullable=False),
    sa.Column('es_fija', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tiempo_planificado', sa.Float(), nullable=False),
    sa.Column('tiempo_estimado_operario', sa.Float(), nullable=True),
    sa.Column('tiempo_total_teorico', sa.Float(), nullable=False),
    sa.Column('peso_aportado', sa.Float(), server_default='0', nullable=False),
    sa.Column('n_articulos_aportados', sa.Float(), server_default='0', nullable=False),
    sa.CheckConstraint('n_articulos_aportados >= 0', name='check_n_articulos_aportados_no_negativo'),
    sa.CheckConstraint('peso_aportado >= 0', name='check_peso_aportado_no_negativo'),
    sa.CheckConstraint('tiempo_estimado_operario > 0', name='check_tiempo_asignacion_positivo'),
    sa.CheckConstraint('tiempo_planificado >= 0', name='check_tiempo_planificado_positivo'),
    sa.CheckConstraint('tiempo_total_teorico > 0', name='check_tiempo_teorico_positivo'),
    sa.ForeignKeyConstraint(['dni_operario'], ['operarios.dni'], ),
    sa.ForeignKeyConstraint(['id_opl'], ['opls.id'], ),
    sa.ForeignKeyConstraint(['semana'], ['repartos.semana'], ),
    sa.PrimaryKeyConstraint('id_opl', 'semana')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asignaciones_opl')
    op.drop_table('opls')
    op.drop_table('operario_articulo')
    op.drop_table('operario_familia')
    op.drop_table('articulos')
    op.drop_table('usuarios')
    op.drop_table('repartos')
    op.drop_table('operarios')
    op.drop_table('familias')
    # ### end Alembic commands ###
