"""Módulo de configuración del sistema."""

from .settings import (
    DATABASE_URL, TEST_DATABASE_URL, BASE_DIR,
    JWT_SECRET_KEY, JWT_ALGORITHM, JWT_EXPIRE_MINUTES,
    CORS_ORIGINS, ENV, IS_PRODUCTION, ADMIN_BOOTSTRAP_PASSWORD,
)

__all__ = [
    'DATABASE_URL', 'TEST_DATABASE_URL', 'BASE_DIR',
    'JWT_SECRET_KEY', 'JWT_ALGORITHM', 'JWT_EXPIRE_MINUTES',
    'CORS_ORIGINS', 'ENV', 'IS_PRODUCTION', 'ADMIN_BOOTSTRAP_PASSWORD',
]
